version: '3'

services:
  vscode:
    build:
      context: .
    image: macroldj/vscode:v1.0.1
    restart: "always"
    ports:
      - '5555:8080'
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 300m
    working_dir: /home/workspace
      - ./vscode/workspace:/home/workspace
    healthcheck:
      test: curl --fail http://localhost:8080||exit 1
      interval: 50s
      timeout: 5s
      retries: 6
